public class Throw {
    public static void main(String[] args) {
        try {
            division();
        } catch (ArithmeticException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    public static void division() throws ArithmeticException {
        int numerador = 10;
        int denominador = 0;

        try {
            int resultado = numerador / denominador;
            System.out.println("El resultado de la divisi√≥n es: " + resultado);
        } catch (ArithmeticException e) {
            throw e;
        }
    }
}